apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: flaskapp
spec:
  pipelineRef:
    name: flaskapp
  resources:
    - name: source
      resourceSpec:
        type: git
        params:
          - name: revision
            value: master
          - name: url
            value: https://github.com/rbalagopalakrishna/flaskapp.git
