apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: flaskapp-pipeline-run
spec:
  serviceAccountName: flaskapp-service
  pipelineRef:
    name: flaskapp-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: flaskapp-git
    - name: flaskapp-image
      resourceRef:
        name: flaskapp-image
