jobs:
  build-and-push:
    executor: docker/docker
    parameters:
      docker-password:
        default: Bbala@123.
        description: |
          Name of environment variable storing your Docker password
        type: env_var_name
      docker-username:
        default: balagopalraj
        description: |
          Name of environment variable storing your Docker username
        type: env_var_name
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: balagopalraj/flaskapp
      - docker/push:
          digest-path: /tmp/digest.txt
          image: balagopalraj/flaskapp
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
orbs:
  docker: circleci/docker@1.3.0
version: 2.1
workflows:
  commit:
    jobs:
      - build-and-push
