#version: 2
#jobs:
#  build:
#    environment:
#      IMAGE_NAME: balagopalraj/flaskapp
#    docker:
#      - image: circleci/buildpack-deps:stretch
#    steps:
#      - checkout
#      - setup_remote_docker
#      - run:
#          name: Build Docker image
#          command: |
#            docker build -t $IMAGE_NAME:latest .
#            docker images
#            echo Bbala@123. | docker login --username balagopalraj --password-stdin
#            docker images
#            docker push $IMAGE_NAME:latest
#workflows:
#  version: 2
#  build-master:
#    jobs:
#      - build:
#          filters:
#            branches:
#              only: master


orbs:
  gke: circleci/gcp-gke@x.y.z
version: 2.1
workflows:
  main:
    jobs:
      - gke/create-cluster:
          cluster: gcp-testing
