apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  selector:
    matchLabels:
      run: flaskapp
  replicas: 1
  template:
    metadata:
      labels:
        run: flaskapp
    spec:
      containers:
      - name: flakapp
        image: flaskapp:latest
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
